name: Amazon Scrapper Bot

on:
  schedule:
    - cron: '30 5 * * *'  # 11:00 AM IST daily
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install gspread oauth2client beautifulsoup4 lxml requests

      - name: Save credentials to file
        run: |
          echo "$GOOGLE_CREDENTIALS" > credentials.json
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDS }}

      - name: Set environment variables
        run: |
          echo "USER_AGENT=${{ secrets.USER_AGENT }}" >> $GITHUB_ENV

      - name: Run Amazon Scraper
        run: python amazon_scrapper.py
