name: Update Google Sheet with Pinterest RSS

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC (5:30 AM IST)
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-sheet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser gspread oauth2client pandas

      - name: Run Pinterest RSS to Sheets script
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: python pinterest_to_sheets.py

      - name: Run Affiliate Link Extraction script
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: python extract_affiliate_links.py